"""add sla_definitions table

Revision ID: 1f2353761580
Revises: 5b7830e25cb0
Create Date: 2026-02-19 14:33:53.094635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2353761580'
down_revision: Union[str, Sequence[str], None] = '5b7830e25cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('statistic', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_definitions_data_source_id'), 'sla_definitions', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_sla_definitions_id'), 'sla_definitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_definitions_id'), table_name='sla_definitions')
    op.drop_index(op.f('ix_sla_definitions_data_source_id'), table_name='sla_definitions')
    op.drop_table('sla_definitions')
    # ### end Alembic commands ###
